project_id = "onsqvrbyjabhdlgsbqfg"

[functions.send-invite]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-map-assist]
verify_jwt = false