export interface EditorTheme {
  id: string;
  name: string;
  emoji: string;
  bg: string;
  dotColor: string;
  edgeColor: string;
  nodeColor: string;
  cardBg: string;
  cardBorder: string;
  cardText: string;
  minimapBg: string;
  minimapNode: string;
  minimapMask: string;
  edgeStrokeWidth: number;
  edgeAnimation: "none" | "dash" | "flow" | "pulse" | "glow" | "neon";
  edgeDashArray?: string;
  edgeOpacity?: number;
}

export const editorThemes: EditorTheme[] = [
  {
    id: "default",
    name: "Padrão",
    emoji: "⚡",
    bg: "hsl(var(--background))",
    dotColor: "hsl(var(--border))",
    edgeColor: "hsl(var(--border))",
    nodeColor: "hsl(var(--primary))",
    cardBg: "hsl(var(--card))",
    cardBorder: "hsl(var(--border))",
    cardText: "hsl(var(--foreground))",
    minimapBg: "hsl(var(--card))",
    minimapNode: "hsl(var(--primary))",
    minimapMask: "hsl(var(--muted) / 0.7)",
    edgeStrokeWidth: 2,
    edgeAnimation: "none",
  },
  {
    id: "workflow",
    name: "Workflow",
    emoji: "⚙️",
    bg: "#1a1a2e",
    dotColor: "#16213e",
    edgeColor: "#00b4d8",
    nodeColor: "#00b4d8",
    cardBg: "#16213e",
    cardBorder: "#0f3460",
    cardText: "#caf0f8",
    minimapBg: "#16213e",
    minimapNode: "#00b4d8",
    minimapMask: "rgba(26, 26, 46, 0.7)",
    edgeStrokeWidth: 2,
    edgeAnimation: "flow",
    edgeDashArray: "10 5",
  },
  {
    id: "neon",
    name: "Neon",
    emoji: "💜",
    bg: "#0a0a0a",
    dotColor: "#1a1a1a",
    edgeColor: "#e040fb",
    nodeColor: "#e040fb",
    cardBg: "#141414",
    cardBorder: "#2a2a2a",
    cardText: "#f3e5f5",
    minimapBg: "#141414",
    minimapNode: "#e040fb",
    minimapMask: "rgba(10, 10, 10, 0.7)",
    edgeStrokeWidth: 2.5,
    edgeAnimation: "neon",
    edgeOpacity: 0.95,
  },
  {
    id: "pastel",
    name: "Pastel",
    emoji: "🎨",
    bg: "#fef7f0",
    dotColor: "#f0e0d0",
    edgeColor: "#c9a9e9",
    nodeColor: "#c9a9e9",
    cardBg: "#ffffff",
    cardBorder: "#e8d5f5",
    cardText: "#5b4a6a",
    minimapBg: "#ffffff",
    minimapNode: "#c9a9e9",
    minimapMask: "rgba(254, 247, 240, 0.7)",
    edgeStrokeWidth: 2,
    edgeAnimation: "none",
  },
  {
    id: "night",
    name: "Noite",
    emoji: "🌙",
    bg: "#0f172a",
    dotColor: "#1e293b",
    edgeColor: "#6366f1",
    nodeColor: "#6366f1",
    cardBg: "#1e293b",
    cardBorder: "#334155",
    cardText: "#e2e8f0",
    minimapBg: "#1e293b",
    minimapNode: "#6366f1",
    minimapMask: "rgba(15, 23, 42, 0.7)",
    edgeStrokeWidth: 2.5,
    edgeAnimation: "glow",
    edgeOpacity: 0.9,
  },
  {
    id: "forest",
    name: "Floresta",
    emoji: "🌲",
    bg: "#0c1a0e",
    dotColor: "#1a3a1e",
    edgeColor: "#22c55e",
    nodeColor: "#22c55e",
    cardBg: "#14291a",
    cardBorder: "#2d5a32",
    cardText: "#d1fae5",
    minimapBg: "#14291a",
    minimapNode: "#22c55e",
    minimapMask: "rgba(12, 26, 14, 0.7)",
    edgeStrokeWidth: 2,
    edgeAnimation: "flow",
    edgeDashArray: "8 4",
  },
  {
    id: "ocean",
    name: "Oceano",
    emoji: "🌊",
    bg: "#0c1929",
    dotColor: "#1a3050",
    edgeColor: "#38bdf8",
    nodeColor: "#38bdf8",
    cardBg: "#132640",
    cardBorder: "#1e4080",
    cardText: "#bae6fd",
    minimapBg: "#132640",
    minimapNode: "#38bdf8",
    minimapMask: "rgba(12, 25, 41, 0.7)",
    edgeStrokeWidth: 2,
    edgeAnimation: "dash",
    edgeDashArray: "6 3",
  },
  {
    id: "sunset",
    name: "Pôr do Sol",
    emoji: "🌅",
    bg: "#1c1017",
    dotColor: "#3d1f2a",
    edgeColor: "#fb923c",
    nodeColor: "#fb923c",
    cardBg: "#2a1520",
    cardBorder: "#5c1a30",
    cardText: "#fde68a",
    minimapBg: "#2a1520",
    minimapNode: "#fb923c",
    minimapMask: "rgba(28, 16, 23, 0.7)",
    edgeStrokeWidth: 2.5,
    edgeAnimation: "pulse",
    edgeOpacity: 0.85,
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    emoji: "🤖",
    bg: "#0d0221",
    dotColor: "#1a0a3e",
    edgeColor: "#0ff0fc",
    nodeColor: "#0ff0fc",
    cardBg: "#150540",
    cardBorder: "#2d1b69",
    cardText: "#e0f7fa",
    minimapBg: "#150540",
    minimapNode: "#0ff0fc",
    minimapMask: "rgba(13, 2, 33, 0.7)",
    edgeStrokeWidth: 2,
    edgeAnimation: "neon",
    edgeOpacity: 0.9,
  },
  {
    id: "blueprint",
    name: "Blueprint",
    emoji: "📐",
    bg: "#0d47a1",
    dotColor: "#1565c0",
    edgeColor: "#bbdefb",
    nodeColor: "#e3f2fd",
    cardBg: "#1565c0",
    cardBorder: "#1976d2",
    cardText: "#e3f2fd",
    minimapBg: "#1565c0",
    minimapNode: "#e3f2fd",
    minimapMask: "rgba(13, 71, 161, 0.7)",
    edgeStrokeWidth: 1.5,
    edgeAnimation: "dash",
    edgeDashArray: "4 4",
  },
  {
    id: "minimal",
    name: "Minimalista",
    emoji: "✨",
    bg: "#fafafa",
    dotColor: "#e5e5e5",
    edgeColor: "#a3a3a3",
    nodeColor: "#171717",
    cardBg: "#ffffff",
    cardBorder: "#e5e5e5",
    cardText: "#171717",
    minimapBg: "#ffffff",
    minimapNode: "#171717",
    minimapMask: "rgba(250, 250, 250, 0.7)",
    edgeStrokeWidth: 1.5,
    edgeAnimation: "none",
  },
];
